// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGameStore.Context;

namespace MyGameStore.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    [Migration("20220119201543_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "liam_farrell@erdmananderson.info",
                            FirstName = "Sadie",
                            Gender = 1,
                            LastName = "Ruecker",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "myrtis@wunsch.ca",
                            FirstName = "Magnus",
                            Gender = 1,
                            LastName = "Ziemann",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "abe@kozey.ca",
                            FirstName = "Felicity",
                            Gender = 1,
                            LastName = "Wilderman",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "reinhold.lang@binskuphal.us",
                            FirstName = "Raul",
                            Gender = 1,
                            LastName = "McGlynn",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "elijah@hyatt.ca",
                            FirstName = "Dominic",
                            Gender = 1,
                            LastName = "Hirthe",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "lauriane.hegmann@strosinritchie.ca",
                            FirstName = "Tate",
                            Gender = 1,
                            LastName = "Rath",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "amya@stroman.co.uk",
                            FirstName = "Genoveva",
                            Gender = 1,
                            LastName = "Harvey",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "cordell.rempel@willmshessel.com",
                            FirstName = "Trinity",
                            Gender = 1,
                            LastName = "Ryan",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "hillard@homenick.us",
                            FirstName = "Kenna",
                            Gender = 1,
                            LastName = "Kreiger",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "hubert.wisoky@jakubowski.name",
                            FirstName = "Andrew",
                            Gender = 1,
                            LastName = "Prosacco",
                            StoreId = 2
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("City")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Haleighshire",
                            IsFranchiseStore = true,
                            Name = "Kadin",
                            Number = "64",
                            Street = "Frami Harbor",
                            Zipcode = "1434"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gregshire",
                            IsFranchiseStore = true,
                            Name = "Creola",
                            Number = "3",
                            Street = "Nikolaus Pike",
                            Zipcode = "1007"
                        },
                        new
                        {
                            Id = 3,
                            City = "Frederikville",
                            IsFranchiseStore = true,
                            Name = "Kenny",
                            Number = "10",
                            Street = "Hessel Walks",
                            Zipcode = "2944"
                        },
                        new
                        {
                            Id = 4,
                            City = "New Laurenville",
                            IsFranchiseStore = true,
                            Name = "Zoila",
                            Number = "72",
                            Street = "Fahey Falls",
                            Zipcode = "2507"
                        },
                        new
                        {
                            Id = 5,
                            City = "Jadeburgh",
                            IsFranchiseStore = true,
                            Name = "Jamey",
                            Number = "9",
                            Street = "Katarina Mill",
                            Zipcode = "1458"
                        },
                        new
                        {
                            Id = 6,
                            City = "New Blancaside",
                            IsFranchiseStore = true,
                            Name = "Sophia",
                            Number = "17",
                            Street = "Terry Mountains",
                            Zipcode = "1352"
                        },
                        new
                        {
                            Id = 7,
                            City = "Milofort",
                            IsFranchiseStore = true,
                            Name = "Alisha",
                            Number = "6",
                            Street = "Schulist Cove",
                            Zipcode = "797"
                        },
                        new
                        {
                            Id = 8,
                            City = "East Monroehaven",
                            IsFranchiseStore = true,
                            Name = "Morris",
                            Number = "38",
                            Street = "Barbara Ridge",
                            Zipcode = "1125"
                        },
                        new
                        {
                            Id = 9,
                            City = "Stammbury",
                            IsFranchiseStore = true,
                            Name = "Kristina",
                            Number = "26",
                            Street = "Cleo Burg",
                            Zipcode = "183"
                        },
                        new
                        {
                            Id = 10,
                            City = "West Price",
                            IsFranchiseStore = false,
                            Name = "Valentin",
                            Number = "12",
                            Street = "Alena Meadows",
                            Zipcode = "116"
                        },
                        new
                        {
                            Id = 11,
                            City = "Williamsonland",
                            IsFranchiseStore = true,
                            Name = "Edgar",
                            Number = "99",
                            Street = "Ahmad Glen",
                            Zipcode = "535"
                        },
                        new
                        {
                            Id = 12,
                            City = "Zolaborough",
                            IsFranchiseStore = true,
                            Name = "Vincenza",
                            Number = "62",
                            Street = "Carter Stream",
                            Zipcode = "766"
                        },
                        new
                        {
                            Id = 13,
                            City = "Eudorashire",
                            IsFranchiseStore = true,
                            Name = "German",
                            Number = "17",
                            Street = "Ernser Fork",
                            Zipcode = "2239"
                        },
                        new
                        {
                            Id = 14,
                            City = "Batzview",
                            IsFranchiseStore = true,
                            Name = "Monserrat",
                            Number = "60",
                            Street = "Isaiah Dale",
                            Zipcode = "742"
                        },
                        new
                        {
                            Id = 15,
                            City = "West Rigobertomouth",
                            IsFranchiseStore = true,
                            Name = "Billie",
                            Number = "85",
                            Street = "Lemke Trail",
                            Zipcode = "1816"
                        },
                        new
                        {
                            Id = 16,
                            City = "New Lourdes",
                            IsFranchiseStore = true,
                            Name = "Norma",
                            Number = "34",
                            Street = "Tad Circle",
                            Zipcode = "997"
                        },
                        new
                        {
                            Id = 17,
                            City = "North Melissa",
                            IsFranchiseStore = false,
                            Name = "Geraldine",
                            Number = "55",
                            Street = "Sheldon Courts",
                            Zipcode = "2853"
                        },
                        new
                        {
                            Id = 18,
                            City = "West Denis",
                            IsFranchiseStore = false,
                            Name = "Rhea",
                            Number = "98",
                            Street = "Celestino Pass",
                            Zipcode = "2533"
                        },
                        new
                        {
                            Id = 19,
                            City = "Predovicshire",
                            IsFranchiseStore = true,
                            Name = "Amber",
                            Number = "90",
                            Street = "Collins Corners",
                            Zipcode = "853"
                        },
                        new
                        {
                            Id = 20,
                            City = "Ebertburgh",
                            IsFranchiseStore = false,
                            Name = "Elwyn",
                            Number = "99",
                            Street = "Mueller Row",
                            Zipcode = "248"
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.HasOne("MyGameStore.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
