// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGameStore.Data.Context;

namespace MyGameStore.Data.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    [Migration("20220119222037_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyGameStore.Data.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bettye@kubreichel.us",
                            FirstName = "Lucinda",
                            Gender = 1,
                            LastName = "Gorczany",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "miguel@tremblay.ca",
                            FirstName = "Emily",
                            Gender = 1,
                            LastName = "Koelpin",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "izabella@bergnaum.biz",
                            FirstName = "Dustin",
                            Gender = 1,
                            LastName = "Krajcik",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "nicolas_kub@yundtbernier.com",
                            FirstName = "Keon",
                            Gender = 1,
                            LastName = "Blick",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "everett_wisozk@wisoky.name",
                            FirstName = "Major",
                            Gender = 1,
                            LastName = "Murphy",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "quentin.senger@abbott.com",
                            FirstName = "Elisa",
                            Gender = 1,
                            LastName = "Boehm",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "gudrun@abshire.name",
                            FirstName = "Karlee",
                            Gender = 1,
                            LastName = "Becker",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "darrick@bergealtenwerth.co.uk",
                            FirstName = "Faustino",
                            Gender = 1,
                            LastName = "Funk",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "johan_swift@crooks.name",
                            FirstName = "Dolores",
                            Gender = 1,
                            LastName = "Kirlin",
                            StoreId = 2
                        },
                        new
                        {
                            Id = 10,
                            Email = "felix_tillman@rippin.us",
                            FirstName = "Kyleigh",
                            Gender = 1,
                            LastName = "Gottlieb",
                            StoreId = 2
                        });
                });

            modelBuilder.Entity("MyGameStore.Data.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addition")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("City")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Port Lauriane",
                            IsFranchiseStore = true,
                            Name = "Milton",
                            Number = "77",
                            Street = "Sam Mews",
                            Zipcode = "2698"
                        },
                        new
                        {
                            Id = 2,
                            City = "New Amiya",
                            IsFranchiseStore = false,
                            Name = "Raoul",
                            Number = "93",
                            Street = "Zemlak Harbor",
                            Zipcode = "1468"
                        },
                        new
                        {
                            Id = 3,
                            City = "West Cortneymouth",
                            IsFranchiseStore = true,
                            Name = "Tony",
                            Number = "49",
                            Street = "Dooley Drives",
                            Zipcode = "2510"
                        },
                        new
                        {
                            Id = 4,
                            City = "South Raystad",
                            IsFranchiseStore = true,
                            Name = "Tavares",
                            Number = "33",
                            Street = "Lowe Skyway",
                            Zipcode = "610"
                        },
                        new
                        {
                            Id = 5,
                            City = "South Rickeyborough",
                            IsFranchiseStore = false,
                            Name = "Jaylon",
                            Number = "7",
                            Street = "Kohler Junction",
                            Zipcode = "1334"
                        },
                        new
                        {
                            Id = 6,
                            City = "Port Milanstad",
                            IsFranchiseStore = false,
                            Name = "Will",
                            Number = "84",
                            Street = "Mireille Park",
                            Zipcode = "2309"
                        },
                        new
                        {
                            Id = 7,
                            City = "New Llewellyn",
                            IsFranchiseStore = true,
                            Name = "Chyna",
                            Number = "82",
                            Street = "Gregory Fork",
                            Zipcode = "442"
                        },
                        new
                        {
                            Id = 8,
                            City = "North Robbieburgh",
                            IsFranchiseStore = false,
                            Name = "Darlene",
                            Number = "84",
                            Street = "Kulas Roads",
                            Zipcode = "228"
                        },
                        new
                        {
                            Id = 9,
                            City = "Reneeshire",
                            IsFranchiseStore = true,
                            Name = "Ashtyn",
                            Number = "19",
                            Street = "Ward Vista",
                            Zipcode = "1611"
                        },
                        new
                        {
                            Id = 10,
                            City = "Hamillshire",
                            IsFranchiseStore = false,
                            Name = "Valentine",
                            Number = "97",
                            Street = "Ritchie Light",
                            Zipcode = "701"
                        },
                        new
                        {
                            Id = 11,
                            City = "Pagacton",
                            IsFranchiseStore = true,
                            Name = "Myrtie",
                            Number = "94",
                            Street = "Witting Lights",
                            Zipcode = "2624"
                        },
                        new
                        {
                            Id = 12,
                            City = "North Zena",
                            IsFranchiseStore = true,
                            Name = "Kathryne",
                            Number = "5",
                            Street = "Breitenberg Road",
                            Zipcode = "336"
                        },
                        new
                        {
                            Id = 13,
                            City = "Kylieland",
                            IsFranchiseStore = false,
                            Name = "Kip",
                            Number = "13",
                            Street = "Hirthe Meadow",
                            Zipcode = "1164"
                        },
                        new
                        {
                            Id = 14,
                            City = "Lake Elnahaven",
                            IsFranchiseStore = false,
                            Name = "Antonio",
                            Number = "96",
                            Street = "Orn Forest",
                            Zipcode = "59"
                        },
                        new
                        {
                            Id = 15,
                            City = "New Kenyaberg",
                            IsFranchiseStore = true,
                            Name = "Enid",
                            Number = "17",
                            Street = "Fletcher Street",
                            Zipcode = "2443"
                        },
                        new
                        {
                            Id = 16,
                            City = "New Germanburgh",
                            IsFranchiseStore = false,
                            Name = "Easter",
                            Number = "85",
                            Street = "Crooks Mill",
                            Zipcode = "2331"
                        },
                        new
                        {
                            Id = 17,
                            City = "Einoshire",
                            IsFranchiseStore = false,
                            Name = "Adela",
                            Number = "51",
                            Street = "Ullrich Burg",
                            Zipcode = "1730"
                        },
                        new
                        {
                            Id = 18,
                            City = "Gusikowskiville",
                            IsFranchiseStore = false,
                            Name = "Alfonso",
                            Number = "61",
                            Street = "Leannon Plains",
                            Zipcode = "2816"
                        },
                        new
                        {
                            Id = 19,
                            City = "Beckerview",
                            IsFranchiseStore = true,
                            Name = "Kiarra",
                            Number = "45",
                            Street = "Hauck Crossing",
                            Zipcode = "2709"
                        },
                        new
                        {
                            Id = 20,
                            City = "Lake Colt",
                            IsFranchiseStore = true,
                            Name = "Jovan",
                            Number = "96",
                            Street = "Amelie Hill",
                            Zipcode = "2357"
                        });
                });

            modelBuilder.Entity("MyGameStore.Data.Model.Person", b =>
                {
                    b.HasOne("MyGameStore.Data.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
